### ISSUE TITLE
Stack traces no longer working

### ISSUE THREAD

**Issue by MylesBorins** [jstime/jstime#34]
Seems like we really do need some sort of basic test runner to avoid regressions like this

It would appear that b7a6d994d3b89288da638ea78f883eb852eb77df regressed our stack trace support

/cc @devsnek

**Comment by MylesBorins** [comment]
Historical stacktrace code for posterity

module: https://github.com/jstime/jstime/commit/b7a6d994d3b89288da638ea78f883eb852eb77df#diff-cc1cadebb5770328d1404803e7a56327L136-L156

script: https://github.com/jstime/jstime/commit/b7a6d994d3b89288da638ea78f883eb852eb77df#diff-420c68e7483ee630e16762977da06437L28-L36

**Comment by EstebanBorai** [comment]
@MylesBorins ohh my majestic creation is broken (?)!

I could check for this if you want me too! I can see theres a PR already indeed.
