### ISSUE TITLE
Compilation failure when installing via `cargo install jstime`

### ISSUE THREAD

**Issue by MylesBorins** [jstime/jstime#74]
```
error: failed to build archive: bad archive: truncated or malformed archive (offset to next archive member past the end of the archive after member counters.o)

error: aborting due to previous error

error: could not compile `rusty_v8`.

To learn more, run the command again with --verbose.
```

This is due to an issue in rusty_v8. Attempted to fix in c911f02 but it didn't stick

Refs: https://github.com/denoland/rusty_v8/pull/543

**Comment by mash-graz** [comment]
this issue could be simply solved by denoland/rusty_v8#543 -- see: denoland/rusty_v8#545 and #8449

**Comment by MylesBorins** [comment]
@mash-graz thanks for the heads up. I think it makes the most sense to wait for this to be fixed upstream and get the fix through an update.

**Comment by mash-graz** [comment]
yes! -- i hope my PR or a similar fix solving the rusty_v8 build system issues will be accepted sooner or later.
it definitely doesn't make much sense to workaround this obvious flaws somewhere else.

**Comment by bartlomieju** [comment]
`rusty_v8` v0.15.0 has been released with the fix from @mash-graz

**Comment by MylesBorins** [comment]
Fixed by https://github.com/jstime/jstime/commit/d66172a5218aa8b300b64c060f9733fe50c0c766
